### ISSUE TITLE
useAuth0() returns undefined when used in custom Apollo Link

### ISSUE THREAD

**Issue by VincentLandais** [auth0/auth0-vue#101]
### Describe the problem

I am using Apollo and I wanted to add an `Authorziation: Bearer` header to my requests using `getAccessTokenSilently`. I do so by adding an auth middleware when creating my ApolloClient. This middleware is called before each request and calls `useAuth0` to get `isAuthenticated` and `getAccessTokenSilently` and sets the headers accordingly. It works fine when using [useQuery](https://v4.apollo.vuejs.org/api/use-query.html) and [useSubscription](https://v4.apollo.vuejs.org/api/use-subscription.html). It does not work however when using [useMutation](https://v4.apollo.vuejs.org/api/use-mutation.html), in this case `useAuth0()` returns undefined. The difference with `useMutation` is that it does not send the request directly but returns a `mutate` function instead. This function is then called manually to send the request. I suspect this issue to be related to #99.

The error:
![Screenshot 2022-03-28 at 10 51 17](https://user-images.githubusercontent.com/100678450/160434075-1144fa73-b530-420d-92f6-7ab48f5ecffc.png)

### What was the expected behavior?

`useAuth0()` returns `isAuthenticated` and `getAccessTokenSilently` instead of `undefined`

### Reproduction

```Javascript
// main.js
import { createApp, provide, h } from 'vue'
import App from './App.vue'

import { ApolloClient, createHttpLink, InMemoryCache, ApolloLink, concat, split } from '@apollo/client/core'
import { WebSocketLink } from "@apollo/client/link/ws";
import { getMainDefinition } from "@apollo/client/utilities";
import { DefaultApolloClient } from '@vue/apollo-composable'

import { createAuth0, useAuth0 } from '@auth0/auth0-vue';

const authMiddleware = new ApolloLink(async (operation, forward) => {
  const { getAccessTokenSilently, isAuthenticated } = useAuth0(); // RETURNS UNDEFINED WHEN EXECUTING MUTATIONS

  if (isAuthenticated.value) {
    const token = await getAccessTokenSilently()
    // add the authorization to the headers
    operation.setContext({
      headers: {
        ...(token ? { authorization: `Bearer ${token}` } : {}),
      }
    });
  }
  return forward(operation);
})

const httpLink = createHttpLink({
  uri: process.env.VUE_APP_GRAPHQL_HTTP_URL,
})

const wsLink = new WebSocketLink({
  uri: process.env.VUE_APP_GRAPHQL_WEBSOCKET_URL,
  options: {
    reconnect: true
  }
});

const link = split(
  ({ query }) => {
    const definition = getMainDefinition(query);
    return (
      definition.kind === "OperationDefinition" &&
      definition.operation === "subscription"
    );
  },
  wsLink,
  httpLink
);

const apolloClient = new ApolloClient({
  link: concat(authMiddleware, link),
  cache: new InMemoryCache(),
})

createApp({
  setup() {
    provide(DefaultApolloClient, apolloClient)
  },

  render: () => h(App),
}).use(createAuth0({
    domain: process.env.VUE_APP_AUTH0_DOMAIN,
    client_id: process.env.VUE_APP_AUTH0_CLIENT_ID,
    audience: process.env.VUE_APP_AUTH0_AUDIENCE,
    redirect_uri: window.location.origin
  }))
  .mount('#app')

```

```Javascript
// Query.vue THIS WORKS
<template>
</template>

<script setup>
import gql from "graphql-tag";
import { useQuery } from '@vue/apollo-composable'

const { result } = useQuery(gql`
    // your query here
`);
</script>
```

```Javascript
// Mutation.vue THIS DOES NOT WORK
<template>
    <button @click="mutate">Execute mutation</button>
</template>

<script setup>
import gql from "graphql-tag";
import { useMutation } from '@vue/apollo-composable'

const { mutate } = useMutation(gql`
    // your mutation here
`);
</script>
```

### Environment

- **Version of `auth0-vue` used:** ^1.0.0
- **Version of `vue` used:** ^3.2.13
- **Which browsers have you tested in?** Firefox, Chrome
- **@apollo/client:** ^3.5.10
- **@vue/apollo-composable:** ^4.0.0-alpha.16
- **graphql:** ^16.3.0
- **graphql-tag:** ^2.12.6
- **subscriptions-transport-ws:** ^0.11.0

**Comment by frederikprijck** [comment]
Thanks for reporting this. I would need to look into this, but I am curious to find out if this is expected behavior from Apollo or not.

If I understand correctly, when using Vue's `inject` in an Apollo Middleware will work for useQuery, while the same code fails for useMutation. This sounds weird behavior from Apollo's side.

That said, I would need to look into this. If you would have a small reproduction sample for this, that would be extremely helpful.

**Comment by VincentLandais** [comment]
Thanks for the response !

I created [this repository](https://github.com/VincentLandais/vue-auth0-apollo-issue-example). It's really straightforward, no configuration is required. Let me know if you have any problem running it.

**Comment by frederikprijck** [comment]
Having looked at it, I can see it is related to the fact that `Apollo` middleware doesn't seem to like using the `inject` API, even for queries this has issues once you start using `refetch`, have a look at https://github.com/VincentLandais/vue-auth0-apollo-issue-example/compare/main...frederikprijck:main.

I think this comes down to what is being discussed in https://github.com/auth0/auth0-vue/issues/99, feel free to chime in in that issue as well as it would be good to get feedback on the different proposed workaround to know how to proceed.

**Comment by VincentLandais** [comment]
Hi @frederikprijck I tried your solution from [your comment on issue #99](https://github.com/auth0/auth0-vue/issues/99#issuecomment-1094650012) but `useAuth0()` still returns undefined. I'm sure I'm missing something. It's my first time using Vue and I don't think I fully understand the problem. Could you help me on this ? 

Here is what I tried: https://github.com/VincentLandais/vue-auth0-apollo-issue-example/commit/079e4000178023bf9585d973472ef5d8d9690ffc

Thanks

**Comment by VincentLandais** [comment]
Nevermind, I think I got it working.

Here's the fix https://github.com/VincentLandais/vue-auth0-apollo-issue-example/commit/6ff52b19e2c93afe938b8609c5a7281951c678db

**Comment by frederikprijck** [comment]
Yep, that's what I was referring to. Not ideal, but should at least allow you to progress without being limitated.
