### ISSUE TITLE
Usage with script setup gives error

### ISSUE THREAD

**Issue by onurusluca** [auth0/auth0-vue#104]
### The problem
I am using Vue 3 Composition Api's script setup. I tried adding a logout function but it gives me an error on console.

The code: 
```
<script setup lang="ts">
import { useAuth0 } from "@auth0/auth0-vue";

const { logout } = useAuth0();
const userLogout = () => {
  logout({ returnTo: window.location.origin });
};
</script>
<template>
          <button @click.prevent="userLogout">
          Logout
          </button>
</template>
```
It gives me this error:

> Uncaught TypeError: Cannot destructure property 'logout' of 'useAuth0(...)' as it is undefined.

### Environment
- **`auth0-vue` : v1.0.0**
- **`vue`: 3.2.31**

**Comment by VincentLandais** [comment]
In my project `useAuth0()` works just fine inside a script setup.
You may have forgotten to do `app.use(createAuth0())` in your `main.js`?

**Comment by onurusluca** [comment]
> In my project `useAuth0()` works just fine inside a script setup. You may have forgotten to do `app.use(createAuth0())` in your `main.js`?

Thanks for the reply. I have a modified version of it in my main.js. 

```
const auth0 = () => {
  createAuth0({
    domain: EnvConfig.authDomain,
    client_id: EnvConfig.authClientId,
    redirect_uri: window.location.origin,
  });
}; 
```

My usage may be wrong.
Is the usage of logout is correct in my code?

**Comment by VincentLandais** [comment]
Your auth0 function should return createAuth0(). Don't forget to call your auth0 function in app.use():
```
const auth0 = () => {
  return createAuth0({
    domain: EnvConfig.authDomain,
    client_id: EnvConfig.authClientId,
    redirect_uri: window.location.origin,
  });
}; 

createApp(App).use(router).use(auth0()).use(pinia).use(i18n).mount("#app");
```

**Comment by frederikprijck** [comment]
@onurusluca , can you provide a reproduction or at least show some more code that gives you the last error you are getting? From the looks of it, this doesn't seems like an issue with the `script setup` itself, but feels like a misconfiguration of some kind.

**Comment by onurusluca** [comment]
@frederikprijck Hi, thanks for the reply.
I just found out my mistake. I was using my old auth0 configuration. I fixed it with the new code.
Thank you!

**Comment by mauveine** [comment]
@onurusluca can you provide the solution? I have a similar problem
