### ISSUE TITLE
Usage with script setup

### ISSUE THREAD

**Issue by onurusluca** [auth0/auth0-vue#105]
### Describe the problem you'd like to have solved
[Script setup](https://vuejs.org/api/sfc-script-setup.html) is becoming more popular and is being the new default. So it would be a good idea to provide usage with it.

### Describe the ideal solution
Adding explanation to the documentation would be a good start.

**Comment by frederikprijck** [comment]
Thanks for reporting this, could you elaborate how those examples would be any different from what we already have regarding the composition API?

**Comment by onurusluca** [comment]
@frederikprijck Hi!
[Script setup](https://vuejs.org/api/sfc-script-setup.html) is becoming a default if you are using composition API. So it would be better if the usage of auth0 is already compatible with script setup. as it is.
Would be easier to use not to write the code again with script setup.

You don't have to rewrite everything. You can just add a section for script setup. Also in the future auth0 may get more complicated as it will grow. So the code will require more tuning.

**Comment by frederikprijck** [comment]
Thanks for the context. I believe we can update the snippets to use the script syntax, especially given the documentation for Composition API mostly starts with explaining the script setup approach.

Happy to review a PR if you like to open one.

>  Also in the future auth0 may get more complicated as it will grow. So the code will require more tuning.

I don't believe it will grow that much. Our Vue SDK is a wrapper around our SPA SDK that exists for a while and is rather mature.

**Comment by onurusluca** [comment]
Will get on it! Thanks!
Sorry I mean Vue SDK not Auth0. 
Vue SDK will receive update and prs and type support etc.
