### ISSUE TITLE
How to use global auth guard

### ISSUE THREAD

**Issue by jpmeijers** [auth0/auth0-vue#109]
https://github.com/auth0/auth0-vue/blob/f459a7ef4b443dc4535aea8d3e745a0f198a327e/README.md?plain=1#L476

Related to https://github.com/auth0/docs/issues/10052

When I do the following, I end up in a redirect loop. How would one use the Auth0 library's auth guard as a global guard (`router.beforeEach(authGuard)`), but exclude the login page?

```
import { createRouter, createWebHistory } from 'vue-router'
import HomeView from '../views/HomeView.vue'
import {authGuard} from "@auth0/auth0-vue";

const routes = [
  {
    path: '/',
    name: 'home',
    component: HomeView
  },
  {
    path: '/login',
    name: 'login',
    component: () => import(/* webpackChunkName: "about" */ '../views/LoginView.vue')
  }
]

const router = createRouter({
  history: createWebHistory(process.env.BASE_URL),
  routes
})

router.beforeEach(authGuard);

export default router
```

**Comment by frederikprijck** [comment]
As our guard is just like any other guard, it will protect any routes it's being registered with. When u use `router.beforeEach`, you are telling it to secure every single route.

As our guard is just like any other guard, it should be aware of routes it should or should not protect. Instead, the consumer should ensure they use our guard only on the routes they want to be protected.

What you want, is something along the lines of this (which is actually not related to our plugin, it's more related to setting up guard using `router.beforeEach`, that you don't want to be registered with every route):

```ts
router.beforeEach((to, from) => {
  if (to.path === '/login') {
    return true;
  }
  return authGuard(to, from);
})
```

Keep in mind that, after navigating to Auth0 to login with Auth0, the user will be redirected back to your application. At that time, the user is still not considered authenticated as our SDK still needs to exchange the tokens before being considered authenticated.
This means Auth0 will need to be redirected back to a public route, so most likely you will need more than only login as a non-protected route.

**Comment by jpmeijers** [comment]
Thanks a lot for this answer. It fills in the gap between the Vue Router docs and the Auth0 tutorial.

What you explain about the redirect after login makes sense. I tested this now and it seems to work even if the root is not public. But for better user experience it would anyway make sense to make the root and /login both public.
