### ISSUE TITLE
TypeError: can't access property "loginWithRedirect" Composition API

### ISSUE THREAD

**Issue by mauveine** [auth0/auth0-vue#118]
### Describe the problem
I am using Vue 3 Composition Api's script setup. I tried adding a loginWithRedirect function but it gives me an error on console.
When I'm using the options API it works just fine.

### What was the expected behavior?

When the function is triggered, should be redirected to Auth0 login page.

### Reproduction

- Added the following code in the main.js
```
app
  .use(router)
  .use(
    createAuth0({
      domain: process.env.VUE_APP_AUTH0_DOMAIN,
      client_id: process.env.VUE_APP_AUTH0_CLIENT_ID,
      redirect_uri: process.env.VUE_APP_AUTH0_REDIRECT_URI
    })
  )
  .use(createPinia())
  .mount('#app')
```
- In the component file
```
<script setup>
import { ref } from 'vue'
import { useAuth0 } from '@auth0/auth0-vue'
import Megamenu from '@/layouts/Megamenu';

let showUserDropdown = ref(false)
let showMegaDropdown = ref(false)
let loggedIn = ref(false)
const { loginWithRedirect } = useAuth0()

function login() {
  loginWithRedirect()
}
</script>
```

- This is the error
![image](https://user-images.githubusercontent.com/9429708/166815712-9dc2901b-87aa-47d5-ae34-3364e1dc5faf.png)

I've tested with hardcoded values instead of the env variables, but the result is the same.

### Environment

- **`auth0-vue`: 1.0.1**
- **`vue` : 3.2.19**
- **Tested in firefox**

**Comment by frederikprijck** [comment]
Thanks for reporting this.
I tried reproducing but haven't been able to do so.

I took our [sample application](https://github.com/auth0-samples/auth0-vue-samples/tree/master/01-Login) and migrated it to use the script setup syntax:

![image](https://user-images.githubusercontent.com/2146903/166883053-cbb98dfd-ef71-467c-a757-6627b9e21d62.png)

Everything seems to work as expected. Any change you can try reproducing it in the above sample?

**Comment by mauveine** [comment]
Thank you for the reply @frederikprijck 
I've tried exactly as in your screenshot and I get the same issue
```
<script setup>
import { ref } from 'vue'
import { useAuth0 } from '@auth0/auth0-vue'
import Megamenu from '@/layouts/Megamenu'

let showUserDropdown = ref(false)
let showMegaDropdown = ref(false)
let loggedIn = ref(false)
const { isAuthenticated, isLoading, user, loginWithRedirect, logout: _logout } = useAuth0()
console.log(isAuthenticated, isLoading, user)

function login() {
  loginWithRedirect()
}

function logout () {
  _logout({
    returnTo: window.location.origin
  })
}
</script>
```

The weird thing is that the Options API works fine, but this happens only when I'm using the composition API.

**Comment by frederikprijck** [comment]
Any chance you can fork the project and apply your changes to demonstrate the problem? Would be happy to look into it and see if we can resolve it.

**Comment by mauveine** [comment]
@frederikprijck 
[Here is a setup](https://github.com/mauveine/auth0vue-example) with yarn.lock and package.json that I have.
I'm using node 14.

**Comment by frederikprijck** [comment]
@mauveine Just to be clear, the Vue version in your project a lot older as the one we use in our SDK.
So I think bumping our package.json isn't necessary, but bumping your project's package.json is.
