### ISSUE TITLE
Can we get more documentation on dealing with multiple Organizations?

### ISSUE THREAD

**Issue by purejgleason** [auth0/auth0-vue#124]
### Describe the problem you'd like to have solved

I am currently trying to handle a business case with multiple organizations. A user can be a member of many of the orgs. I would like to understand how to handle having the user select which org they want to be part of. Currently the only docs I see suggest passing an org id but I would rather them select one from a dropdown.

### Describe the ideal solution

The login screen provides a dropdown to select the org the person would like to log in as

## Alternatives and current work-arounds

I think you could probably use the management API to get all orgs and create a custom login screen but I would like to avoid this as it sounds like a lot of work.

**Comment by frederikprijck** [comment]
Thanks, the alternative work around is the current recommended way if you want the user to select an organization. That goes beyond our SDK, as our SDK doesn't do anything with the login page, other then redirecting the user to it.

I understand this isn't ideal. However, I would recommend contacting your support contact and pass the info, as the request here is actually a request for Auth0 server, and not our SDK.

Closing for now, as this isn't something we can do anything about from our SDK.

**Comment by frederikprijck** [comment]
When u change the organization, you need to ensure you call `loginWithRedirect` using the new `organization`, that's not a limitation of our SDK but of how organization's work, you need to go through an interactive login (calling `loginWithRedirect` when switching organizations).
