### ISSUE TITLE
Accessing isAuthenticated from outside component

### ISSUE THREAD

**Issue by jdalrymple** [auth0/auth0-vue#135]
### Describe the problem

**Not sure this is a bug, so feel free to correct me**

When accessing the isAuthenticated property outside of a component (which should be supposed as of 1.0.1), the return is a proxy variable that doesnt return the boolean expected.

Code Sample:

authfile.js
```js
import { createAuth0 } from "@auth0/auth0-vue";

export const auth = createAuth0({
  domain: "dev-xxxxxxxx.auth0.com",
  client_id: "123456",
  redirect_uri: "http://localhost:3000",
});
```

middleware file (middleware/auth.js)
```js
import {auth} from "../authfile";

export default defineNuxtRouteMiddleware(async (to, from) => {
  let isAuthenticated = auth.isAuthenticated

  console.log(isAuthenticated)
  ...
});
```

Output:
![console.log(auth.isAuthenticated)](https://user-images.githubusercontent.com/3743662/183097687-65a99ad2-fe08-4485-bc69-540489f4e3b9.png)

### What was the expected behavior?

Return true/false

### Reproduction

(Ill make a sample project and share in a moment!)

### Environment

- **Version of `auth0-vue` used:**    "@auth0/auth0-vue": "^1.0.2",
- **Version of `vue` used:** 3
- **Which browsers have you tested in?**: chrome, firefox (latest of each)
- **Other modules/plugins/libraries that might be involved:**  "nuxt": "3.0.0-rc.3",

**Comment by frederikprijck** [comment]
Hey,

That's expected. This is a `ref` value from Vue and it doesn't automatically unref when used outside of a component. U should be able to unref it and get its value:

```
console.log(unref(auth.isAuthenticated));
```

That should give you the correct output.

**Comment by jdalrymple** [comment]
Ah ok! thank you!!

**Comment by jdalrymple** [comment]
Follow up, similar problem (which may not be a problem)

calling auth.loginWithRedirect() after that above code in the middleware, returns a 'TypeError: can't access property "loginWithRedirect", this._client is undefined' Is this also to be expected?

**Comment by frederikprijck** [comment]
Not that I am aware of no. If you could provide a reproduction we can have a look at what's going on.

**Comment by jdalrymple** [comment]
https://github.com/jdalrymple/auth0-vue-test 

I created this example project, give it a look when you have a chance!

**Comment by frederikprijck** [comment]
Our SDK is not built for Nuxt. If you want to use it with Nuxt, please refer to https://debbie.codes/blog/nuxt-add-vue-plugins/.
