### ISSUE TITLE
auth0-vue with Ionic Vue Capacitor

### ISSUE THREAD

**Issue by donniekerr** [auth0/auth0-vue#139]
### Describe the problem

You do not provide an option to just ask a question.  Need to know how to configure auth0-vue to work in a Vue.js app built using Ionic-Vue Capacitor so that the redirect works inside the native app and returns the user to the app.

### What was the expected behavior?

redirect after login returns user to native app, not external browser

### Reproduction

**Can the behavior be reproduced using the [Vue SDK Playground](https://github.com/auth0/auth0-vue/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

### Environment

- **Version of `auth0-vue` used:**
- **Version of `vue` used:**
- **Which browsers have you tested in?**
- **Other modules/plugins/libraries that might be involved:**

**Comment by frederikprijck** [comment]
Hey,

We don't have any guidance on Vue with Ionic yet, but we do for Angular and React and I assume it would be comparable for Vue.

Instead of calling `loginWithRedirect`, you should use:

```
import { Browser } from '@capacitor/browser';

// Ask auth0-react to build the login URL
const url = await buildAuthorizeUrl();
// Redirect using Capacitor's Browser plugin
await Browser.open({ url });
```

Would that help?

**Comment by donniekerr** [comment]
Got the react sample to work like you show here.  Trick was to get the uri format correct and add it as a custom url in the plist of the iOS app
