### ISSUE TITLE
Have a way to check if the default access token has a scope

### ISSUE THREAD

**Issue by jrgleason** [auth0/auth0-vue#146]
### Describe the problem you'd like to have solved

I have a page that I would like to add some administration functionality. From the UI side I need to determine if a user is allowed based (has an access token with) a scope. 

### Describe the ideal solution

So for example I will have an "admin" scope and I would like to show this "button" if the user has an "admin" scope. This would be similar to the IdTokenClaims option. 

## Alternatives and current work-arounds

Use the get access token methods to get a token then use the jwt-decode library as a computed to check if the token has the proper scopes.

**Comment by frederikprijck** [comment]
Hey,

An Access Token is not supposed to be parsed in the client side. It's intended to be used when calling APIs.

More information on this: https://auth0.com/docs/secure/tokens

More specifically:

> Your application should not attempt to decode them or expect to receive tokens in a particular format.

Therefore, this is not a request we can accommodate for.

Typically, u can either ensure the scopes exist in the id token (using a rule), or create your own HTTP call in the API that returns the required information based on the provided access token.
