### ISSUE TITLE
Cypress e2e tests

### ISSUE THREAD

**Issue by ahelord** [auth0/auth0-vue#148]
Hello dear developers, I would like to know how I can do e2e tests with this package, that is, do a programmatic login and then read the token in Vue 3 and with this library login without doing a redirect.

**Comment by frederikprijck** [comment]
It's recommended to do a redirect. I know Cypress has mentioned you should avoid that in the past. However, at Auth0 we have a close connection with the Cypress team and they have reconsidered their recommendation for platforms like Auth0 and the like.

More info on this:

- https://youtu.be/WrcDNZsYqrQ
- https://github.com/cypress-io/cypress-documentation/pull/4439
- https://github.com/cypress-io/cypress/pull/18075

You can find our examples here: https://github.com/auth0/auth0-vue/tree/main/cypress

**Comment by ahelord** [comment]
@frederikprijck  hi, the video is not available

**Comment by frederikprijck** [comment]
Sorry about that, here is the correct link: https://www.youtube.com/watch?v=Fohrq5GZSD8
