### ISSUE TITLE
Navigation aborted from to via a navigation guard

### ISSUE THREAD

**Issue by sghgh1996** [auth0/auth0-vue#161]
### Describe the problem
I am using authGuard for protecting routes. When I reload the website after the webpage is reloaded, it is redirected to "/". for example: http://localhost:3333/overview is replaced with http://localhost:3333. The error shown in console is **Error: Navigation aborted from "/" to "/overview" via a navigation guard.** It is an error of vue-router navigation guard. It seems the auth guard returns false. This issue only happens in Safari and firefox and in chrome it works fine.

### What was the expected behavior?
After reloading on each page, it must not redirect to "/" pages.

### Reproduction
I use vitessg for creating vue app and I add authGuard for all the routes (All routes are protected).
I think the issue happens because navigation guard returns false on [this line](https://github.com/auth0/auth0-vue/blob/main/src/guard.ts#L18).

**Can the behavior be reproduced using the [Vue SDK Playground](https://github.com/auth0/auth0-vue/blob/master/DEVELOPMENT.md#the-sdk-playground)?** No

### Environment

- **Version of `auth0-vue` used: 1.0.1**
- **Version of `vue` used: 3.2.33**
- **Which browsers have you tested in? Firefox - Safari**
- **Other modules/plugins/libraries that might be involved: vite-ssg**

**Comment by frederikprijck** [comment]
Thanks for reaching out.

The line you point out that is returning false, is expected to be returning false. What would you expect it to return when you are not authenticated ?

Keep in mind, the idea of the guard is to block access to any route when the user is not authenticated. So if the user is not authenticated, we try to authenticate and if that doenst work, we will return false.

Can you provide a reproduction sample for us to look into in order to get a better understanding of the issue at hand?

**Comment by sghgh1996** [comment]
Actually it is working correctly in chrome but not in safari, firefox and chrome incognito. Then I'd assume it a strange behavior. I read in the [docs](https://github.com/auth0/auth0-vue/blob/main/EXAMPLES.md#protecting-a-route) that vue-router must be registered before auth0-vue. However this is not happening in vite-ssg. See [this line](https://github.com/antfu/vite-ssg/blob/main/src/client/index.ts#L76). Vite-ssg first await for the call back function which our modules such as auth0, i18n, etc are registered and afterwards it registers vue-router.
Could it be the origin of the problem? because I replaced vite-ssg with vue createApp and now it works without this problem.

**Comment by frederikprijck** [comment]
That does sound like a possible cause if the problem, but I am not familiar with vite-ssg to know for sure.

Closing this as it seems like it works fine with vue createApp, but can always reopen if you believe there is something we should do on the side of the SDK. Please do provide a minimal reproduction of the issue, so we can easily reproduce and look into the behavior.
