### ISSUE TITLE
Argument of type 'Auth0Plugin' is not assignable to parameter of type 'Plugin_2'

### ISSUE THREAD

**Issue by TheSerumDev** [auth0/auth0-vue#172]
I use version 1.0.2 of auth0-vue the ionic vue version is 6.0.0. 

I don't know what to write because in the title my problem is already explained. Here is a code screenshot so you can see what I did

-- Screenshot --
 https://prnt.sc/ugysF-rUN6wP

**Comment by Rytiggy** [comment]
Same issue here
