### ISSUE TITLE
SDK redirects to / even though redirectUri is set

### ISSUE THREAD

**Issue by jakon89** [auth0/auth0-vue#173]
### Describe the problem

I have below component function that is called once the user clicks "login" button:
```ts
function login() {
  loginWithRedirect({
    organization: "ABC",
    redirect_uri: window.location.origin + "/authed",
    audience: 'cba'
  });
}
```

with the below app setup:
```ts
let auth0Plugin = createAuth0({
    domain: "ABC",
    client_id: "xxxx",
    redirect_uri: window.location.origin + "/authed",
    audience: 'cba'
});

app.use(
    auth0Plugin
);
```

The problem is that once the user is authenticated he is redirected to `http://myapp.com/authed` but then is quickly moved to `/`. My gut feeling says that if redirect uri is set when redirecting the user to the Auth0 frontend then the `/authed` should be the final step in the whole flow. I do not understand why this library is hijacking URL and moving user to `/`

I think the code responsible for above lives in https://github.com/auth0/auth0-vue/blob/166a1795feb545bf7af6d2d6e238860ca4db2b5d/src/plugin.ts#L151

The question is how to stop that? I want `/authed` to be the final destination for the login flow where I want to execute more actions with the fetched token.
### What was the expected behavior?
User lands on `/authed` and is not moved to `/` once `/authed` is rendered.

### Reproduction

**Can the behavior be reproduced using the [Vue SDK Playground](https://github.com/auth0/auth0-vue/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

### Environment

- **Version of `auth0-vue` used:** latest
- **Version of `vue` used:** 3 
- **Which browsers have you tested in?** firefox
- **Other modules/plugins/libraries that might be involved:** no

**Comment by frederikprijck** [comment]
Thanks for reaching out, this is covered in our [FAQ](https://github.com/auth0/auth0-vue/blob/main/FAQ.md#3-user-is-

> The question is how to stop that? I want /authed to be the final destination for the login flow where I want to execute more actions with the fetched token.

I believe the snippet above should achieve that, however, it could make sense to separate the route that is used to handle the redirect callback from actual application, as it might not work well with our AuthGuard, knowing that [our AuthGuard does use `appState.target`](https://github.com/auth0/auth0-vue/blob/main/src/guard.ts#L15-L17), we know those won't ever use the `redirect_uri` as their final destination, instead the flow would end up on the protected route.

**Comment by jakon89** [comment]
I should have seen this before 🤦‍♂️ Anyway it makes sense now, thanks a lot for the quick help.
