### ISSUE TITLE
Can't get `useAuth0` working for my own guard

### ISSUE THREAD

**Issue by Bastczuak** [auth0/auth0-vue#185]
### Describe the problem you'd like to have solved
I want to have access to the authenticated user object to check the users roles to decide whenever I want to route with an guard. Unfortionally right now `useAuth0` always returns `undefined` at this point.

```js
import { authGuard } from '@auth0/auth0-vue'

const nonPartnerGuard = (to, from, next) => {
  const { user } = useAuth0() // Cannot destructure property 'user' of 'useAuth0(...)' as it is undefined

  if (!user["https://custom-fields.com/roles"]?.includes('partner')) {
    return next('/no-partner')
  }
  return next()
}

const routes = [
  {
    path: '/:pathMatch(.*)*',
    redirect: '/',
  },
  {
    path: '/',
    name: 'overview',
    component: NoName,
    beforeEnter: [authGuard, nonPartnerGuard],
  },
  {
    path: '/no-partner',
    name: 'noPartner',
    component: () => import('@/views/NoPartner'),
    beforeEnter: authGuard,
  },
]

const router = createRouter({
  history: createWebHistory(process.env.BASE_URL),
  routes,
})


```
It seems like it has something to do with `inject` which does not provide an usage outside of a component.

### Describe the ideal solution
Beeing able to use `useAuth0` outside of components like shown in my upper example.

Here is my code snippet how I handled this in Vue 2 with the spa-sdk.

```js
// src/auth0.js

import Vue from 'vue'
import { createAuth0Client } from '@auth0/auth0-spa-js'

let instance

const getAuth0Instance = () => instance

const useAuth0 = () => {
  instance = new Vue({
    ...
    computed: {
      normalizedUser () {
        const keyEndsWith = s => Object.keys(this.user).find(key => key.endsWith(s))
        const roles = this.user[keyEndsWith('roles')]
        return {
          roles,
        }
      },
    },
    async created () {
      this.auth0Client = await createAuth0Client(...)
      this.user = await auth0Client.getUser()
    },
    ...
  })

  return instance
}

const Auth0Plugin = {
  install (Vue, options) {
    Vue.prototype.$auth0 = useAuth0(options || {})
    if (options?.component) {
      Vue.component('CAccount', options.component)
    }
  },
}

export {
  Auth0Plugin,
  getAuth0Instance,
}

// src/guards.js

import { getAuth0Instance } from './auth0'

const nonPartnerGuard = (to, from, next) => {
  const authService = getAuth0Instance()
  const user = authService.normalizedUser

  if (!user.roles?.includes('partner')) {
    return next('/no-partner')
  }
  return next()
}

export {
  nonPartnerGuard,
}


```

## Alternatives and current work-arounds
No known workaround. If you can provide one I would be happy!

**Comment by frederikprijck** [comment]
Thanks for reaching out.

It's intended for `useAuth0` to only be usable in components, and not outside of the components, as it uses the composition API.
If you need to roll your own Guard, you can always look at how we built [our own guard](https://github.com/auth0/auth0-vue/blob/main/src/guard.ts), which is also without `useAuth0`.

**Comment by Bastczuak** [comment]
@frederikprijck so I then take the reference created by `createAuth0` and pass it around?

**Comment by frederikprijck** [comment]
Thats not what our guard is doing. You can use the globalProperties to access it.

Regardless, this isnt specific to our SDK but common in vue.

But yes, you can also pass around the value returned by createAuth0 if you like.

**Comment by jenjen75** [comment]
Hello @frederikprijck  do you think the implementation of `useAuth0` could be used outside a component in the future ?
Pinia, an official vue 3 state management, can be use anywhere : https://pinia.vuejs.org/core-concepts/outside-component-usage.html

auth0-vue library is awesome, have this feature could help a lot of developper to use the SDK the same way in component or outside (auth0 is commonly needed in fetch or axios interceptor to add Authorization or Cookie Header)

Thank you,

**Comment by frederikprijck** [comment]
Thanks for sharing that, we are always open to improve our SDK and make integrating it more easy.

Not something we can prioritise at the current time, but we are always open to review a PR if you would want to implement this.
