### ISSUE TITLE
Where is the documentation for RedirectLoginOptions in @auth0/auth0-vue

### ISSUE THREAD

**Issue by BasilaryGroup** [auth0/auth0-vue#187]
### Describe the problem

The documentation for [@auth0/auth0-vue](https://auth0.github.io/auth0-vue/index.html) is missing documentation for the interface RedirectLoginOptions 

### What was the expected behavior?

I expected to be able to click to the RedirectLoginOptions from [here](https://auth0.github.io/auth0-vue/interfaces/Auth0VueClient.html#loginWithRedirect).

### Reproduction

1. click  [here](https://auth0.github.io/auth0-vue/interfaces/Auth0VueClient.html#loginWithRedirect)
2. How do I see the documentation for the interface RedirectLoginOptions? There is no link.

**Comment by frederikprijck** [comment]
Thanks, this is solved on our beta branch and will be released as part of the GA release of v2, which should be in a couple of weeks.
