### ISSUE TITLE
Unable to use auth0 variables in <script>

### ISSUE THREAD

**Issue by stephenstuder** [auth0/auth0-vue#190]
### Describe the problem you'd like to have solved

Example code
```
<script setup>
import {useAuth0} from '@auth0/auth0-vue'
import {onMounted} from 'vue'

const {user, isAuthenticated, isLoading, loginWithRedirect} = useAuth0()

onMounted(() => {
  if (!isAuthenticated) {  // <---- returns proxy
    loginWithRedirect()
  }
})
<script>
```
In this situation `isAuthenticated` does not work as intended, same with `user`. Auth0 variables return proxies when used in the <script>. If there is a workaround to process the proxy, can it please be listed out in the docs? All examples in the docs just show use of auth0 variables in the template

### Describe the ideal solution

Clear documentation on how to use auth0 variables in vue <script>

## Alternatives and current work-arounds

I imagine there are ways to process the proxy in javascript that I could implement, but it seems like a common enough use that the docs should cover it.

**Comment by stephenstuder** [comment]
If recommended approach is shared I am happy to make a PR adding documentation that covers it.

**Comment by frederikprijck** [comment]
These proxies are Vue Reactivity Proxies, so it behaves just like any other Vue Reactivity proxy. Could you elaborate on what's different here that does not allow you to use the same approach as you would with other Vue Reactivity proxies ?

**Comment by stephenstuder** [comment]
Yeah apologies, got spoiled by svelte and now am confused using ref vue variables. How would you approach the snippet above? Should there be docs showing example snippets of using auth0 variables in the script?

Apologies, I know it's not on you to demonstrate how vue works, but is seems relevant to using this plugin correctly.

**Comment by frederikprijck** [comment]
> How would you approach the snippet above? 

As explained in https://vuejs.org/api/reactivity-advanced.html#toraw:

```
<script setup>
import {useAuth0} from '@auth0/auth0-vue'
import {onMounted} from 'vue'

const {user, isAuthenticated, isLoading, loginWithRedirect} = useAuth0()

onMounted(() => {
  if (!toRaw(isAuthenticated)) { 
    loginWithRedirect()
  }
})
<script>
```

> Should there be docs showing example snippets of using auth0 variables in the script?

I don't think so. Our docs is not the place to learn vue. That said, we do plan to see if it makes sense to move all examples to use the script setup syntax.

**Comment by frederikprijck** [comment]
So the proxy holds a ref, and the ref holds a value. So what you want is `if (!toRaw(isAuthenticated).value) { `. 

If you believe we are doing something that's uncommon in our SDK, we are happy to improve.

**Comment by stephenstuder** [comment]
Sounds good, appreciate the time, hopefully this thread helps others that get tripped up.

**Comment by stephenstuder** [comment]
Man, I guess I am just no good at vue 3. Its endlessly difficult to get data anywhere other than the template..

`console.log(auth0)`
![Screen Shot 2023-01-30 at 4 35 36 PM](https://user-images.githubusercontent.com/55567604/215621122-a1038e61-72d0-4b4e-9003-e953fff6f19e.png)

`console.log(auth0._user)`
![Screen Shot 2023-01-30 at 4 37 19 PM](https://user-images.githubusercontent.com/55567604/215621372-751d8261-85f4-49e7-8ad9-2e04a4e4f8b7.png)

 `console.log(auth0._user.value)`
![Screen Shot 2023-01-30 at 4 38 37 PM](https://user-images.githubusercontent.com/55567604/215621428-e360cde6-e34d-485f-9cf6-e8e0ca78e6e9.png)

`console.log(JSON.parse(JSON.stringify(auth0._user.value)))`
![Screen Shot 2023-01-30 at 4 39 29 PM](https://user-images.githubusercontent.com/55567604/215621612-85b31f60-6a8f-4b43-bead-45fe343bfe78.png)

` console.log(JSON.parse(JSON.stringify(auth0._user)))`
![Screen Shot 2023-01-30 at 4 41 25 PM](https://user-images.githubusercontent.com/55567604/215621821-deb7a8a6-6097-442b-a7f6-cd4a32a98a3c.png)

**Comment by frederikprijck** [comment]
Hey @stephenstuder ,

As mentioned, we are happy to improve where needed. So if u believe we are doing something incorrect, we are open to improve. But would need to elaborate abit more on how we are doing things in a way that isn't common in vue if you believe that is the case.

What we are doing is what's shown here: https://vuejs.org/api/reactivity-core.html#readonly
We have a `ref` (the example has `reactive`, but that doesn't work for non-objects so we use `ref`), and we want to expose it as `readonly`.

Having said that, the issue here is again about Proxies and Ref's.

If I understand correctly, you want to use `toRaw(auth0.user).value`. The reason you need this is the following:

- to use proxy objects outside of reactive context, you can use [`toRaw`](https://vuejs.org/api/reactivity-advanced.html#toraw), this will give u the original object and not the proxy.
- the original object is a Ref, whose value can be read by accessing the value property.

So if you want to retrieve the user's name, you can use:

```
const user = toRaw(auth0.user).value;
console.log(user.name);
```

As our SDK is built for Vue3, we focus on the composition API, but it's also possible to use it with the Options API. If you however need to use our values outside of the context of a component, you need to do a bit of work.

I agree that it would be easier if we would just have a user object, but we don't. We have a reactive API instead. If you don't want that, you need to pull the data out of the reactive context as mentioned above. The pattern for this should always be the same.

**Comment by frederikprijck** [comment]
I added a section to our FAQ to elaborate on this, if you want you can give the PR a review and can address things you believe aren't clear.

**Comment by stephenstuder** [comment]
I appreciate the help, however the result of the snippet was `undefined`. I'll keep trying to find out what the issue is, and i'll review that PR was well.

`const user = toRaw(auth0.user).value;
console.log(user.name);`

For now I have a hacky solution of using an @load listener in the template to call a pinia action and set state.

**Comment by frederikprijck** [comment]
If you would have something for me to look at, I would be happy to do so. I tried this on our playground application and it logged the user's name as soon as I am logged in.

**Comment by stephenstuder** [comment]
Sure, here is the general setup. I do not have access to expand the allowed urls. So I had to leave the createAuth0 variables false. Hopefully you have test ones you can fill in.

Once those are filled in, the use case I am trying to solve is in user.js

https://codesandbox.io/s/solitary-frog-mpwspt?file=/src/auth0.js

**Comment by frederikprijck** [comment]
I had some issues with codesandbox, and downloading the sample doesnt run with issues related to pinia.

What I do see is that the configuration is wrong ,if you are using v2 (which u are), you need to use:

```
export const auth0 = createAuth0({
  domain: "",
  clientId: "",
  authorizationParams: {
    audience: ""
  }
});
```

Would that change anything? If not, can you provide something that's runnable for me to look into without solving compilation issues? Thanks

**Comment by frederikprijck** [comment]
I managed to get the codesandbox running and I can see the undefined, I will look into it, thanks.

**Comment by frederikprijck** [comment]
I managed to get it running on codesandbox and can see the undefined.

It's a timing issues. You are logging the user before it's been set. The reactive API we use is to be able to react to changes, Vue will ensure it updates the component/UI whenever a reactive property changes. When u exit that you are on your own and need to ensure you call it at the correct time.

To test, just wrap it with a setTimeout:

```
  setTimeout(() => {
    const userData = toRaw(auth0.user).value;
    console.log(userData.name);
  }, 5000);
```

I am not saying this is a solution, but what I am saying is that this is why we use a reactive API.

**Comment by frederikprijck** [comment]
Here is a codesandbox showing what I mean: https://codesandbox.io/s/fragrant-pine-cvetm4

I added a login button tho, to avoid a continues redirect. But it outputs my name after logging in and coming back without a timeout, but ensuring we do not access the properties by exiting reactive API before isLoading is false.

**Comment by stephenstuder** [comment]
Great find, it is indeed a timing issue, I was able to get my name to print with a Timeout!

Also yes I agree you do not need to cover each of these edge cases in the readme, If someone is stuck in a similar situation they will figure out a way into a thread like this. 

Thanks for you prompt replies and troubleshooting. This SDK has been a joy to work with in the app I am building, just hit those few edge cases that ended up being more about fundamental vue concepts more than the SDK.
