### ISSUE TITLE
Nuxt3 yarn generate fail with : [500] Named export 'createAuth0' not found

### ISSUE THREAD

**Issue by nicolas-bastien** [auth0/auth0-vue#197]
### Describe the problem

Auth0-vue is working on development environnement but fails on generation for deployment.
Context : 
- Nuxt3
- SSR = true
- Node version 16

### What was the expected behavior?

'createAuth0' should be recognized.

### Reproduction

I've setup the plugin wich register a middleware on Nuxt3 this way : 
// plugins/auth.ts

import { createAuth0 } from '@auth0/auth0-vue'

```js
export default defineNuxtPlugin((nuxtApp) => {
  const auth0 = createAuth0({
    domain: '...',
    clientId: '...',
    authorizationParams: {
      redirect_uri: '.../auth-callback'
    }
  })
...
}
```
I've got this error on yarn generate :

> [500] Named export 'createAuth0' not found. The requested module 'file:///home/nicolas/www/smartbooster/smartbooster/smartbooster-inside/node_modules/@auth0/auth0-vue/dist/lib/auth0-vue.cjs.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
> 
> import pkg from 'file:///home/nicolas/www/smartbooster/smartbooster/smartbooster-inside/node_modules/@auth0/auth0-vue/dist/lib/auth0-vue.cjs.js';
const { createAuth0 } = pkg;

If I try the pkg way : 

> "default" is not exported by "node_modules/@auth0/auth0-vue/dist/auth0- vue.production.esm.js", imported by "plugins/auth.ts".
> file: /home/nicolas/www/smartbooster/smartbooster/smartbooster-inside/plugins/auth.ts:1:0
> 1: import pkg from '@auth0/auth0-vue'
>    ^
> 2: const { createAuth0 } = pkg;

Does somebody have an idea ?

Thanks 
Nicolas

**Can the behavior be reproduced using the [Vue SDK Playground](https://github.com/auth0/auth0-vue/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

### Environment

```json
"devDependencies": {
    "@nuxt-themes/docus": "^1.6.0",
    "nuxt": "^3.1.0"
  },
  "dependencies": {
    "@auth0/auth0-vue": "^2.0.0"
  }
```

- **Version of `auth0-vue` used:** 
- **Version of `vue` used:** Nuxt3
- **Which browsers have you tested in?** localy on command line + on Netlify
- **Other modules/plugins/libraries that might be involved:** Clean install with docus theme

**Comment by frederikprijck** [comment]
Thanks for reaching out.

We have no explicit support for nuxt, but happy to accept any changes that make this work for you without breaking others.

As it works when developing, there has to be something about nuxt when you prepare for deployment.

I can try and see what is causing that when i have time. In the meantime, happy to accept any PR that both explains and solves it.

Thanks,

**Comment by nicolas-bastien** [comment]
Hi @frederikprijck,

Thanks, I'm not so good in javascript so I'm not sure I'll be able to PR.
(I'm CEO of my agency and use Nuxt with Auth0 for all internal documentations)
But if it helps, I can make a repo to reproduce the problem on github ?

**Comment by frederikprijck** [comment]
That would definetly help, thanks for willing to do that!

**Comment by nicolas-bastien** [comment]
Hi @frederikprijck,

Here is a fresh repository to reproduce : https://gitlab.com/nicolas-bastien/nuxt3-auth0

I set up the CI in a previous MR to act it's ok.
Then in this MR : https://gitlab.com/nicolas-bastien/nuxt3-auth0/-/merge_requests/2
I added the plugin for auth0-vue and a callback page.

You can see the error directly in the CI job : https://gitlab.com/nicolas-bastien/nuxt3-auth0/-/jobs/3687916579
If if at the end gitlab sais job is successful, pages are not generated and we only have 404 after deployment.

Thanks a lot for your help
Nicolas

**Comment by frederikprijck** [comment]
Thanks.

As the build output shows 

> [error] [nuxt] [request error] [unhandled] [500] Named export 'createAuth0' not found. The requested module 'file:///builds/nicolas-bastien/nuxt3-auth0/node_modules/@auth0/auth0-vue/dist/lib/auth0-vue.cjs.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from 'file:///builds/nicolas-bastien/nuxt3-auth0/node_modules/@auth0/auth0-vue/dist/lib/auth0-vue.cjs.js';

Did doing that solve anything?

**Comment by nicolas-bastien** [comment]
@frederikprijck yes

I try to be clear in the description but maybe not enough.

If I try the pkg way :

"default" is not exported by "node_modules/@auth0/auth0-vue/dist/auth0- vue.production.esm.js", imported by "plugins/auth.ts".
file: /home/nicolas/www/smartbooster/smartbooster/smartbooster-inside/plugins/auth.ts:1:0
1: import pkg from '@auth0/auth0-vue'
^
2: const { createAuth0 } = pkg;

I'm not good enough in javascript to go any deeper.

**Comment by frederikprijck** [comment]
> I try to be clear in the description but maybe not enou

No, I should have seen that, apologies. I will investigate this further!

**Comment by frederikprijck** [comment]
I opened a PR that should solve this. To verify could you do the following (you will need to do this locally):

- open `node_modules/@auth0/auth0-vue/package.json` and add the following in the same way as in the PR

```json
"exports": {
    ".": {
      "require": "./dist/lib/auth0-vue.cjs.js",
      "import": "./dist/auth0-vue.production.esm.js",
      "types": "./dist/typings/index.d.ts"
    }
  },
```

Then run `yarn generate`.

This is just to verify if the change works for you as well. This is ofcourse not a fix that you can use, you will need to wait on a new release, but happy to cut one as soon as we merge the PR.

**Comment by nicolas-bastien** [comment]
@frederikprijck it's perfectly working locally !
I have tested with my real project.
yarn generate works and the authentication with auth0 too.

Great you're my hero today !

So if I understand, you will ping me when the new release is ready ?
I don't have so much pression on my project so you can take the time to do as you need.

**Comment by frederikprijck** [comment]
@nicolas-bastien v2.0.1 of auth0-vue has been released and should include the fix needed to work with Nuxt 3.

Having said that, and as much as I like you are using our SDK. I also recommend looking into https://auth.nuxtjs.org/providers/auth0, which is a built-in way to integrate Auth0 with Nuxt (we are not involved with that, so can not help but it should work better in Nuxt).

**Comment by nicolas-bastien** [comment]
@frederikprijck thanks a lot.

I tried a lot of things before reaching you.
nuxt-auth is good but only working on Nuxt2, the new community bundle for Nuxt3 does not work with SSR.

So auth0-vue is the only solution and a pretty simple one by the way.

Thanks again and if you have PHP / Symfony problem one day, i'll be happy to help ;-)

**Comment by nicolas-bastien** [comment]
Hi @frederikprijck,

I updated my project this morning with the news release and deployed to Netlify.
I confirm everything is working fine !

Thanks

**Comment by frederikprijck** [comment]
Thank you for confirming!

**Comment by jpcarpenter** [comment]
@nicolas-bastien could you share the full implementation of your `auth.ts` plugin and how you are using `useAuth0()` inside a component? I'm having a similar issue, and have tried just about every "fix" mentioned here.

**Comment by nicolas-bastien** [comment]
@jpcarpenter here is my auth.ts

```ts
import { createAuth0 } from '@auth0/auth0-vue'

export default defineNuxtPlugin((nuxtApp) => {
  const auth0 = createAuth0({
    domain: 'xxxxxxxxxx.eu.auth0.com',
    clientId: 'xxxxxxxxxx',
    authorizationParams: {
      redirect_uri: 'https://my-domain.app/auth-callback'
    }
  })

  if (process.client) {
    nuxtApp.vueApp.use(auth0)
  }

  addRouteMiddleware('auth', () => {
    if (useRoute().path === '/auth-callback' || process.env.NODE_ENV === 'development') {
      return
    }

    if (process.client) {
      auth0.checkSession()
      if (!auth0.isAuthenticated.value) {
        auth0.loginWithRedirect({
          appState: {
            target: useRoute().path,
          }
        })
      }
    }
  }, {'global': true})
})

```

With a dummy page auth-callback.vue

I use that to make an internal site for my agency so I use it on every page with the middleware.
I don't have any auth component.

I hope this will help you !

**Comment by jaywilburn** [comment]
@nicolas-bastien  can you show me how you are using this in the app? Like where are you calling login and logout? Also, are you using this within Pinia? I am making a similar setup and would love some insight there

**Comment by RHellenes** [comment]
> @jpcarpenter here is my auth.ts
> 
> ```ts
> import { createAuth0 } from '@auth0/auth0-vue'
> 
> export default defineNuxtPlugin((nuxtApp) => {
>   const auth0 = createAuth0({
>     domain: 'xxxxxxxxxx.eu.auth0.com',
>     clientId: 'xxxxxxxxxx',
>     authorizationParams: {
>       redirect_uri: 'https://my-domain.app/auth-callback'
>     }
>   })
> 
>   if (process.client) {
>     nuxtApp.vueApp.use(auth0)
>   }
> 
>   addRouteMiddleware('auth', () => {
>     if (useRoute().path === '/auth-callback' || process.env.NODE_ENV === 'development') {
>       return
>     }
> 
>     if (process.client) {
>       auth0.checkSession()
>       if (!auth0.isAuthenticated.value) {
>         auth0.loginWithRedirect({
>           appState: {
>             target: useRoute().path,
>           }
>         })
>       }
>     }
>   }, {'global': true})
> })
> ```
> 
> With a dummy page auth-callback.vue
> 
> I use that to make an internal site for my agency so I use it on every page with the middleware. I don't have any auth component.
> 
> I hope this will help you !

When I try to use equivalent setup I end up with an infinite loop of logins. This is because when the middleware runs the `if (!auth0.isAuthenticated.value) {` is true. 

Have you experienced anything similar?

**Comment by nicolas-bastien** [comment]
> @nicolas-bastien can you show me how you are using this in the app? Like where are you calling login and logout? Also, are you using this within Pinia? I am making a similar setup and would love some insight there

@jaywilburn I gave up and move the deployment to gitlab pages so I can benefit their authentication system.

**Comment by frederikprijck** [comment]
> When I try to use equivalent setup I end up with an infinite loop of logins. This is because when the middleware runs the if (!auth0.isAuthenticated.value) { is true.

Any difference if you also take isLoading into account? You need to ensure you do not check if isAuthenticated before isLoading is false.

@nicolas-bastien, based on the thread, it seemed as if you got everything working. If that's not the case, do know you can always reach out.

**Comment by RHellenes** [comment]
> @nicolas-bastien, based on the thread, it seemed as if you got everything working. If that's not the case, do know you can always reach out.

I think the problem is that I can't listen to isLoading. When the routeMiddleware is running the isLoading is true, and will assume that it won't change. 

Is there a way to make hook into the underlying fetch and make it async or something?

I think I got it working with this package @auth0/auth0-spa-js following this guide: https://javascript.plainenglish.io/nuxt-3-auth0-authentication-70e86a98a3b3 but I would prefer to get it working with this package tbh.

**Comment by frederikprijck** [comment]
Auth0-Vue (This SDK) is nothing but a small wrapper around Auth0-SPA-JS (the SDK in that thread) to easily integrate with Vue. As Nuxt works a bit differently, I would argue using straight up Auth0-SPA-JS makes sense and simplify things.

Having said that, if it works with Auth0-SPA-JS, it should work with Auth0-Vue as well, as as I said Auth0-Vue uses Auth0-SPA-JS. However what I believe the issue to be in your case is because instead that we convert the Promise (from Auth0-SPA-JS) to a Reactive Property (Auth0-Vue) which doesn't work well with Nuxt, but works well with Vue.

**Comment by RHellenes** [comment]
> Having said that, if it works with Auth0-SPA-JS, it should work with Auth0-Vue as well, as as I said Auth0-Vue uses Auth0-SPA-JS. However what I believe the issue to be in your case is because instead that we convert the Promise (from Auth0-SPA-JS) to a Reactive Property (Auth0-Vue) which doesn't work well with Nuxt middleware (which is as designed), but works well with Vue.

Yeah that change would make the issue I am experiencing. I will continue forth with Auth0-SPA-JS as per your recommendation then! 

Just a thought; could it be possible to leverage the authGuard() which serves the same purpose in a vue-app?
