### ISSUE TITLE
Infinite loop when error is thrown inside custom auth0 action

### ISSUE THREAD

**Issue by ikovac** [auth0/auth0-vue#208]
### Describe the problem

When an error is thrown inside the custom post-login auth0 action, I get an infinite loop and there is no way to properly handle the custom action error.
I think that loop is happening inside route guard:
```js
async function createGuardHandler(client: Auth0VueClient, to: RouteLocation) {
  const fn = async () => {
    if (unref(client.isAuthenticated)) {
      return true;
    }

    await client.loginWithRedirect({
      appState: { target: to.fullPath }
    });

    return false;
  };

  if (!unref(client.isLoading)) {
    return fn();
  }

  await watchEffectOnceAsync(() => !unref(client.isLoading));

  return fn();
}
```
Because `loginWithRedirect` redirects back to the home page which is protected by auth0 guard and then the guard is called again and the `client.isAuthenticated` is still false and `loginWithRedirect` is called again. 
My url after action throws an error looks like this: `http://localhost:8000/?error=access_denied&error_description=Something%20went%20wrong.%20Please%20try%20again&state=something...`.

*When I make home page public and put guard on some other route there is no loop because I am redirected to the home page which has no route guard

### What was the expected behavior?

Expected behavior is to be able to catch $auth0 plugin error and handle it without being stuck inside loop.

### Reproduction
In order to reproduce it, add custom post-login action that throws an error and create vue 3 app with home page that is protected with auth0 guard.
Post-login action should be somethig like:
```js
exports.onExecutePostLogin = async (event, api) => {
  return api.access.deny(ERROR_MESSAGE);
};
```

### Environment

- **Version of `auth0-vue` used:** 2.0.1
- **Version of `vue` used:** 3.2.45
- **Which browsers have you tested in?** chrome, brave
- **Other modules/plugins/libraries that might be involved:** vue router v4

**Comment by frederikprijck** [comment]
Thanks, you should never redirect back to a route that's guarded to only allow acess to authenticated users. You should redirect back to a public, unprotected route. Typically, this could be a temporary "/callback" route.

This is also the case outside of errors, you need to give the SDK the time to set the authentication state, which happens asynchronously. So you should never provide a redirect_uri that is protected by our AuthGuard.

**Comment by ikovac** [comment]
Woww, thanks @frederikprijck for the very fast response!
Basically, all my routes are protected and I have no public routes (even not a login screen because it is owned by Auth0). Should I create a public route (and set it for redirect_uri) whose only purpose would be to redirect to the home page if the user is authenticated and otherwise handle that error and show it to the user?

**Comment by frederikprijck** [comment]
Correct, that's what you want. 👍  I updated my comment above to reflect the behavior you should look for.

**Comment by frederikprijck** [comment]
> whose only purpose would be to redirect to the home page if the user is authenticated 

Well, homepage, or the route accessed that's using our Guard. But our SDK should take care of that for u.

**Comment by ikovac** [comment]
Thanks a lot for your help! 🚀

**Comment by frederikprijck** [comment]
Closing, feel free to continue conversation if needed!
