### ISSUE TITLE
Lib somehow breaks Vite HMR

### ISSUE THREAD

**Issue by DeeJayTC** [auth0/auth0-vue#210]
### Describe the problem

I had some issues with HMR not working, ie content on the browser not being refreshed. 
Turns out the moment I add and initialize the auth0-vue lib it stops  working. 

### What was the expected behavior?

HMR should work with auth0-vue installed

### Reproduction

- **Version of `auth0-vue` used:** 2.0.1
- **Version of `vue` used:** 3.2.31
- **Which browsers have you tested in?** Chrome
- **Other modules/plugins/libraries that might be involved:** vuetify, vite-plugin-vuetify

**Comment by frederikprijck** [comment]
Thanks for reaching out.

We have [our own sample that uses vite](https://github.com/auth0-samples/auth0-vue-samples), and HMR appears to be working fine for me. 

<img width="473" alt="image" src="https://user-images.githubusercontent.com/2146903/219224865-b44eae57-0f30-4ec1-ab3d-9a83aabf14c4.png">

Could you try our sample application and verify it works for you or not? 

Thanks.

**Comment by DeeJayTC** [comment]
Yea i can see its working in there just tried it. 

In my scenario HMR is working completely fine but the moment I just add the
createAuth0 stuff to main.ts HMR stops working. 

I removed all login pages etc anything that could cause trouble and realized that hmr breaks the moment I have Auth0 initialized and added to vue. Tried all other plugins one by one to see which one is causing the issues. 

I'll try the exact vue/vuetify etc versions you have in your sample, lets see if its some sort of version mismatch on my end.

**Comment by DeeJayTC** [comment]
Hey @frederikprijck i'll close this one, it really seems to be some sort of version mismatch. 
I used the exact versions your samples are using and its working fine in there. 
The moment I switch back to the vue version I was using (think it  was 3.1.17 and  you have 3.1.23) the problem is back. 

Thanks tho...sorted :)
