### ISSUE TITLE
CommonJS file is bundled by default using vue-cli

### ISSUE THREAD

**Issue by aKzenT** [auth0/auth0-vue#215]
### Describe the problem
When using vue-cli to build a project using auth0-vue, the common JS file is used instead of the ESM file. This causes problems as the CommonJS file does not include things like the authGuard function.

Without changing anything else, using version 2.0.1 and 2.0.2 cause the CJS version to be bundled, while version 2.0.0. Interestingly enough this only happens when doing a production build. "vue-cli serve" works as expected.

I believe the change is due to this PR https://github.com/auth0/auth0-vue/pull/201 that was merged with verison 2.0.1. This would also explain why the @auth0-spa library is loaded correctly:
![image](https://user-images.githubusercontent.com/2589184/221245930-1d4eab51-b690-4c0e-ba09-ae8a4aa4b634.png)

### What was the expected behavior?
ESM file is included.

### Environment
- **Version of `auth0-vue` used:** 2.0.2
- **Version of `vue` used:** 3
- **Which browsers have you tested in?**
- **Other modules/plugins/libraries that might be involved:** vue-cli

**Comment by frederikprijck** [comment]
Thanks for reporting. I was unable to reproduce this.

What I tried was the following:

- npm install -g @vue/cli
- vue create my-project
- cd my-project
- npm install @auth0/auth0-vue

Then, I ensured our SDK is imported and used, including the authGuard.

Both `vue-cli-service build` and `vue-cli-service serve` works.

Could you provide something for us to reproduce this so we can see how we can solve this?

**Comment by aKzenT** [comment]
Hm. I did the same as you using the latest @vue/cli (5.0.8). I use the default settings for vue3.

Then in main.js I added these lines:

```
import { authGuard } from "@auth0/auth0-vue";

console.log(authGuard);
```

Nothing else.

Then I run `npm run serve -- --mode test` (mode is important) and watch the sources panel in chrome:

![image](https://user-images.githubusercontent.com/2589184/222745194-0418e840-ea56-4510-a638-3bd3d1a39c05.png)

Also the console.log displays "undefined".

**Comment by frederikprijck** [comment]
Thanks, can you elaborate why you want to run the app in a mode that's for running tests ?

It works when mode is either development or production, but I dont think you are intended to serve using test mode.

**Comment by aKzenT** [comment]
This is probably an error on our side. The developer wanted to ensure a NODE_ENV of "test" for a staging environment, not realizing that this actually targets unit tests. Thanks for pointing that out. We will fix that on our side.

That being said, I still think there is a problem, isn't there? Why is the CJS build picked in "test" mode while @auth0-spa-js and other dependencies correctly load as ESM? And why is the authGuard not defined in the CJS build?

**Comment by frederikprijck** [comment]
> Why is the CJS build picked in "test" mode while @auth0-spa-js and other dependencies correctly load as ESM? And why is the authGuard not defined in the CJS build?

Thanks, will look into why that's happening!
