### ISSUE TITLE
Can we use auth0-vue to setup an auth0lock

### ISSUE THREAD

**Issue by qixiaojian310** [auth0/auth0-vue#222]
I want to use auth0lock, I have already know how to use it, but I don't know how to use auth0-vue to combine with it to build an embedded application.

**Comment by frederikprijck** [comment]
No, this SDK does not support lock and we have no intention to support that.

If you want to use lock, I suggest to use lock directly and create your own Vue wrapper.

However, we do recommend sticking to Auth0-Vue and rely on Auth0's Universal Login Page.
