### ISSUE TITLE
Uncaught error when error thrown inside custom Auth0 Action

### ISSUE THREAD

**Issue by freddiescadding** [auth0/auth0-vue#223]
### Describe the problem

When an error is thrown inside a custom post-login auth0 action, our unauthenticated callback URI `/auth/callback` is throwing an error and not being redirected. 

The URL is: `http://localhost:8009/auth/callback?error=access_denied&error_description=my_custom_error_msg&state=XXX`

Error is:
```
Uncaught (in promise) Error: my_custom_error_msg
    at ee.handleRedirectCallback (auth0-spa-js.production.esm.js:1:31086)
    at plugin.ts:128:20
    at ae.__proxy (plugin.ts:166:22)
    at ae.handleRedirectCallback (plugin.ts:127:17)
    at ae.__checkSession (plugin.ts:140:33)
    at ae.install (plugin.ts:66:10)
    at Object.use (runtime-core.esm-bundler.js:4399:28)
    at main.ts:40:5
```

I'm not sure whether I am meant to be catching this error myself in the application or whether the SDK should be catching the error [here](https://github.com/auth0/auth0-vue/blob/38f143346c2702e830887597dfb2d09c0e7b90f0/src/plugin.ts#L140).

### What was the expected behavior?

Based on [this function](https://github.com/auth0/auth0-vue/blob/main/src/plugin.ts#L135-L150) and [this function](https://github.com/auth0/auth0-vue/blob/38f143346c2702e830887597dfb2d09c0e7b90f0/src/plugin.ts#L163-L175), I expected this to set an `error` value on the plugin, and reload the URL from `appState`.

### Reproduction

Add a custom post-login action that throws an error, and create a Vue 3 app with an unauthenticated callback URL. 
Post-login action e.g.:

```
exports.onExecutePostLogin = async (event, api) => {
  return api.access.deny('my_custom_error_msg');
};
```

### Environment

- **Version of `auth0-vue` used:** 2.1.0
- **Version of `vue` used:** 3.2.47
- **Which browsers have you tested in?** Chrome, Safari
- **Other modules/plugins/libraries that might be involved:** Vue Router v4.0.3

**Comment by frederikprijck** [comment]
It looks like the checkSession method does not use the proxy, so errors aren't caught as you expect.

Will look into fixing this, thanks.

**Comment by freddiescadding** [comment]
> It looks like the checkSession method does not use the proxy, so errors aren't caught as you expect.
> 
> Will look into fixing this, thanks.

Thanks @frederikprijck, much appreciated!

**Comment by freddiescadding** [comment]
@frederikprijck Please could you provide a rough timeframe estimate for this fix, so that my team can decide whether to pause or abort our current migration to this package? Many thanks for your help

**Comment by frederikprijck** [comment]
Thanks, I was looking into this, but it might be a breaking change to avoid throwing the error. People may be relying on it. So I am not sure we can change the behavior.

Can you help me understand why this would result in aborting to migrate to our SDK?

**Comment by freddiescadding** [comment]
> Thanks, I was looking into this, but it might be a breaking change to avoid throwing the error. People may be relying on it. So I am not sure we can change the behavior.

If it is the intended behaviour of the SDK, wouldn't breaking changes still be appropriate for a new vsn if documented in the Changelog?

> Can you help me understand why this would result in aborting to migrate to our SDK?

We are using a different vue/auth0 SDK at the moment, but have decided to move towards the `auth0/auth0-vue` SDK for a few reasons. We will need to decide if having to add a workaround for this issue impacts whether we still wish to make the migration at this time. It would still be our preference to complete this migration. Thanks

**Comment by freddiescadding** [comment]
Thanks @frederikprijck I have tested this. Because this is now just swallowing the error, the user is no longer redirected from the callback URL. Would we expect the desired behaviour to be as I outlined in the `What was the expected behavior?` section above: namely that the SDK would add the error to the `errors` property but still continue to reload the route stored in `appState`? The flow of the `__checkSession()` fn seems to be that even in the case of an `error` query param from Auth0, the router will still be pushed to its original target.

Thanks for your help with this!

**Comment by freddiescadding** [comment]
The way that our callback route is set up, which I believe is the intended way, is that it is expected for the SDK to perform a redirect from that route. If I were to add a workaround to handle your proposed PR, I imagine I would perform my own redirect in the case of `error/error_description` params being present. However, I would imagine that sometimes these params may be present but not resulting in an internal SDK error, and so the SDK would successfully then redirect on its own. I would need to be able to reliably identify scenarios in which the SDK is not performing the redirect itself. Hope that makes sense!

**Comment by frederikprijck** [comment]
> I would imagine that sometimes these params may be present but not resulting in an internal SDK error

Any error present in the URL will cause the SDK to throw an error, see: https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L501

The user should most likely not be redirected to `appState.target` when `handleRedirectCallback` failed. We only redirect back to `appState.target` when it was successful.

What we could do is have the SDK take an errorPath, which we would use to redirect to in this case. That would be the same as how our Angular SDK works: https://github.com/auth0/auth0-angular/blob/master/projects/auth0-angular/src/lib/auth.service.ts#L100

**Comment by freddiescadding** [comment]
Oh ok, perfect! Well that works I think - if we can guarantee that the presence of `error` query param results in this scenario, as drafted in your PR, then we can handle the redirect at that route. The `errorPath` suggestion sounds ideal, but I'm happy with a quick fix if easier for you!

**Comment by frederikprijck** [comment]
I am not sure you can, as the presence of an error doesnt indicate it happend at this time.

So ye ... every error in the URL results in the error set internally. But not every error being set comes from an error param in the URL.

**Comment by frederikprijck** [comment]
I have updated the PR to include an errorPath, would be great it you can have another look.

Once the PR is merged, we can pretty much cut a release instantly, which should unblock you 👍

**Comment by freddiescadding** [comment]
@frederikprijck I've tested this and am very happy with the solution. Thanks so much for your help with this!

**Comment by frederikprijck** [comment]
Releases as 2.2.0, didn't go with a patch release because of the fact that we are adding errorPath. Arguably could have been a patch, but went with a minor.

Thanks again for reporting this!

**Comment by freddiescadding** [comment]
@frederikprijck Thanks so much for moving so quickly on this 😊
