### ISSUE TITLE
Vue SDK Doesn't Handle Org Invitation Redirects

### ISSUE THREAD

**Issue by jdscolam** [auth0/auth0-vue#231]
### Checklist

- [X] The issue can be reproduced in the [auth0-vue sample app](https://github.com/auth0-samples/auth0-vue-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-vue#readme), [Examples](https://github.com/auth0/auth0-vue/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-vue/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-vue/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-vue/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When receiving a routed callback with an organization invitation (e.g.` https://127.0.0.1:8080/invitations?invitation={code}&organization{code}`) the `auth0.loginWithRedirect({organization: 'code', invitation: 'code'})` does not properly redirect to the invitation acceptance flow, therefore you need to manually drive to that URL.  In addition the redirect after acceptance doesn't automatically get turned into a login by the Vue Auth0 SDK.

### Reproduction

1. Create an Auth0 SPA app with organizations enabled and the login url set to an https localhost (e.g. https://127.0.0.1:port/invitations)
2. Install the Vue Auth0 sample app and add a new route to handle the invitation redirects
3. Add a new Vue component to receive the redirect and check to make sure that organization and invitation are sent on the query string
4. Attempt to use auth0.loginWithRedirect({...}) to pass the invitation and organization
5. Notice that the redirect is sent to the login flow not the invitation acceptance flow
6. When manually directing to the authorize/ endpoint notice how the login flow does not complete

### auth0-vue version

2.2.0

### Vue version

3.0.0

### Which browsers have you tested in?

Chrome, Other

**Comment by frederikprijck** [comment]
Hello,

Can you please try `auth0.loginWithRedirect({ authorizationParams: { organization: 'code', invitation: 'code' }})`, with v2 of the SDK (which you are using), any property that needs to get sent to Auth0 has to be put in the `authorizationParams`.

Relevant docs: https://auth0.github.io/auth0-vue/interfaces/AuthorizationParams.html

Let me know if that helps.

**Comment by jdscolam** [comment]
Yup, that worked, thank you!

That being said it's REALLY poorly documented.  Would you please update the Vue.js docs to cover the invitation flow/scenario?  

Also, please allow the Application Login URI to be https://localhost... for dev purposes.  Having to workaround with an IP is a nightmare.

**Comment by frederikprijck** [comment]
Thanks, we will update the docs to improve this.

Regarding localhost, that works. I work and test using localhost everyday, not using any ip such as 127.0.0.1, so no idea why that wouldnt work for you. 

Regardless, not something our SDK controls.

**Comment by jdscolam** [comment]
@frederikprijck Sad to say when I delete that entry I get the following error when creating an invitation: "A default login route is required to generate the invitation url. For more information, see https://auth0.com/docs/universal-login/configure-default-login-routes"

**Comment by frederikprijck** [comment]
Oh, apologies. It is in fact required for invitations I believe yes., but not for general login, my bad.

I would recommend providing product feedback over [here](https://auth0.com/feedback), as this is not something we control from our SDK side.
