### ISSUE TITLE
Generated typescript declaration for `Auth0VueClient.user` and `Auth0VueClient.idTokenClaims` is incorrect regarding `undefined`

### ISSUE THREAD

**Issue by SimonSimCity** [auth0/auth0-vue#237]
### Checklist

- [X] The issue can be reproduced in the [auth0-vue sample app](https://github.com/auth0-samples/auth0-vue-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-vue#readme), [Examples](https://github.com/auth0/auth0-vue/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-vue/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-vue/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-vue/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The type declaration bundled with the code on npm contains incorrect typings for `Auth0VueClient.user` and `Auth0VueClient.idTokenClaims`.

Here's an excerpt of the code which I found in the package downloaded from npm:
```ts
export interface Auth0VueClient {
    /**
     * Contains the information of the user if available.
     */
    user: Ref<User>;
    /**
     * Contains all claims from the id_token if available.
     */
    idTokenClaims: Ref<IdToken>;
}
```

But according to what I see here in the repo (https://github.com/auth0/auth0-vue/blob/main/src/interfaces/auth0-vue-client.ts), both of them should be a `Ref` also allowing `undefined` as value.

### Reproduction

1. Install the package `@auth0/auth0-vue` in version `2.2.0`.
2. Check the typing for `user` and `idTokenClaims` on the interface `Auth0VueClient`.

### Additional context

-/-

### auth0-vue version

2.2.0

### Vue version

3.3.4

### Which browsers have you tested in?

Other

**Comment by frederikprijck** [comment]
Thanks, this was fixed but not yet released.  I will cut a release today.
