### ISSUE TITLE
need an example to redirect to signup page using new universal login

### ISSUE THREAD

**Issue by cookiejest** [auth0/auth0-vue#247]
### Checklist

- [X] The issue can be reproduced in the [auth0-vue sample app](https://github.com/auth0-samples/auth0-vue-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-vue#readme), [Examples](https://github.com/auth0/auth0-vue/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-vue/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-vue/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-vue/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I cant seem to find a way to redirect to the signup page by default. The other ways seem to require to use the old style universal login that looks dated. Do you have an example of how to do that with this library?

### Reproduction

trying   this.loginWithRedirect({ authorizationParams: { screen_hint: "signUp" },

only works with old universal not new.

### auth0-vue version

latest

### Vue version

latest

### Which browsers have you tested in?

Chrome, Firefox

**Comment by frederikprijck** [comment]
Thanks for reaching out.

You need to use `signup`, not `signUp`.

More info on this can be found here: https://auth0.com/docs/authenticate/login/auth0-universal-login/new-experience#signup

**Comment by cookiejest** [comment]
tried that, doesn't seem to be functional?

**Comment by frederikprijck** [comment]
It seems to work for me when using the new login experience.

Can you verify you see the `screen_hint` set to `signup` in the network tab for the request to `/authorize`?

**Comment by cookiejest** [comment]
Hmm yeh. It worked now. I must have done something in the auth0 UI to disable it somehow when I checked the first time
