### ISSUE TITLE
docs: Token Endpoint Authentication Method does not exist on Application settings

### ISSUE THREAD

**Issue by schalkneethling** [auth0/auth0-vue#251]
### Checklist

- [X] The issue can be reproduced in the [auth0-vue sample app](https://github.com/auth0-samples/auth0-vue-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-vue#readme), [Examples](https://github.com/auth0/auth0-vue/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-vue/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-vue/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-vue/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

In the `README` of the repository, there is the following line:

```
Ensure that "Token Endpoint Authentication Method" under "Application Properties" is set to "None"
```

When navigating to this page in the Dashboard, the only options under "Application Properties" are, "Application Logo" and "Application Type". Doing a text search of the page also does not yield this string.

### Reproduction

1. Log into the Dashboard.
2. Click on Applications
3. Click on the three-dot menu for the relevant application.
4. Choose settings.
5. Scroll down to the "Application Properties" section.
6. There is no "Token Endpoint Authentication Method" option to set.

### auth0-vue version

2.2.0

### Vue version

nuxt: 3.5.1 with vue: latest

### Which browsers have you tested in?

Chrome

**Comment by ewanharris** [comment]
Hey @schalkneethling, that setting has recently been moved under a separate tab that is only shown if the value is set to a value other than `none`, we'll update that note in our readme.

**Comment by frederikprijck** [comment]
Closing as this is fixed.

**Comment by schalkneethling** [comment]
> Hey @schalkneethling, that setting has recently been moved under a separate tab that is only shown if the value is set to a value other than `none`, we'll update that note in our readme.

Thanks so much.

**Comment by Rinololz** [comment]
So how am I supposed to set the Token Endpoint Auth Method to something other than none if the option is not visible unless its already set to something other than none?
