### ISSUE TITLE
Preserve `error` and `error_description` query params when using `errorPath`

### ISSUE THREAD

**Issue by dahu33** [auth0/auth0-vue#297]
### Checklist

- [X] The issue can be reproduced in the [auth0-vue sample app](https://github.com/auth0-samples/auth0-vue-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-vue#readme), [Examples](https://github.com/auth0/auth0-vue/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-vue/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-vue/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-vue/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Shouldn't the `errorPath` option preserves the `error` and `error_description` query params to keep context on the error (https://auth0.com/docs/authenticate/login/auth0-universal-login/error-pages#parameters)? 

The issue is here: https://github.com/auth0/auth0-vue/blob/bd61487bcd639e32544969c57e64c7e203a36d87/src/plugin.ts#L185

### Reproduction

Probably, the easiest way to reproduce this is to have a Post Login action that denies access.

### auth0-vue version

2.3.1

### Vue version

3.3.6

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
Hello,

We have an example on how to handle errors in our repository: https://github.com/auth0/auth0-vue/blob/main/EXAMPLES.md#error-handling

Can you help me understand what doesn't work for you in this case?

**Comment by dahu33** [comment]
After trying to use the `authGuard`, the `errorPath` option, and the error handling method mentioned above,  it appears that the `authGuard` creates an infinite redirection loop as it doesn't handle the error case and just call `loginWithRedirect` blindly. Please advise...

**Comment by frederikprijck** [comment]
https://github.com/auth0/auth0-vue/blob/main/FAQ.md#4-getting-an-infinite-redirect-loop-between-my-application-and-auth0

You should not redirect back to a protected route. A protected route means you can only access it when logged in, bit when being redirected back from Auth0 we are either:

- Not yet logged in as we still need to fetch a token
- Will never be logged in because of an error

Therefor, you need to ensure you redirect back to a non-protected route to handle the callback.

**Comment by frederikprijck** [comment]
Closing as I think this has been answered. Feel free to ping me if not.
