### ISSUE TITLE
Use export type and import type to allow verbatimModuleSyntax

### ISSUE THREAD

**Issue by DavidDeSloovere** [auth0/auth0-vue#302]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-vue#readme), [Examples](https://github.com/auth0/auth0-vue/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-vue/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-vue/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-vue/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Starting with Nuxt 3.8, `verbatimModuleSyntax` is enabled by default.
This needs all types to be exported and imported with an explicit `type`.

https://nuxt.com/blog/v3-8#type-import-changes

One of the errors:
![image](https://github.com/auth0/auth0-vue/assets/352626/29981a65-0b39-4966-a626-33c18d0813c6)

### Describe the ideal solution

I'm no Typescipt expert, but the new `verbatimModuleSyntax` option added in TS v5 seems to be preferred going forward.

### Alternatives and current workarounds

Workaround is to disable `verbatimModuleSyntax` for now.

**Comment by frederikprijck** [comment]
Thanks, that makes sense. Will look into this.

**Comment by DavidDeSloovere** [comment]
That was fast! Already updated and it works as expected now. Thanks. 👍
