### ISSUE TITLE
Incorrectly redirecting when both code and state search params are set

### ISSUE THREAD

**Issue by Petri-Oosthuizen** [auth0/auth0-vue#326]
### Checklist

- [X] The issue can be reproduced in the [auth0-vue sample app](https://github.com/auth0-samples/auth0-vue-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-vue#readme), [Examples](https://github.com/auth0/auth0-vue/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-vue/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-vue/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-vue/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The `auth0-vue` plugin redirects when both `code` and `state` are specified as URL search parameters.

I have another callback URL using those parameters which has nothing to do with auth0.

### Reproduction

Please find a working reproduction here: [codesandbox](https://codesandbox.io/p/devbox/dawn-smoke-vck7s6).

Keep an eye on the URL while clicking on the following links in the sandbox:
1. Navigate to `/example?code=a` -> the URL is changed correctly
2. Navigate to `/example?state=r` -> the URL is changed correctly
3. Navigate to `/example?code=a&state=r` -> redirects to "/"

### auth0-vue version

2.3.2

### Vue version

3.3.9

### Which browsers have you tested in?

Chrome, Firefox

**Comment by frederikprijck** [comment]
Thanks, you can set `skipRedirectCallback: window.location.pathname === '/other-callback'` to ensure we do not read the param in certain scenarios.

**Comment by frederikprijck** [comment]
Because it was added in a non breaking way based on feedback like your scenario, initially we handled every request.

**Comment by Petri-Oosthuizen** [comment]
Ok thank you. Just as an aside, the documentation you linked to is incorrect with the usage:
```
createAuth0({
  skipRedirectCallback: window.location.pathname === '/other-callback' // <- not a clientOption
})
```
it should instead be:
```
  createAuth0(
    {
      ...
    },
    {
      skipRedirectCallback: window.location.pathname === "/other-callback", <- a plugin option
    },
  );
  ```

**Comment by frederikprijck** [comment]
Thanks, fixed in https://github.com/auth0/auth0-vue/pull/327
