### ISSUE TITLE
Redirect to / when trying to access user object from useAuth0()

### ISSUE THREAD

**Issue by dukesteen** [auth0/auth0-vue#87]
### Describe the problem
When I navigate to a route that's different from the project root, and try to access the user object from `useAuth0()`, it redirects me back to the project root (or whichever url is provided as the redirect_uri in the `createAuth0()` options. It still keeps the right component but updates the url.

### What was the expected behavior?
Being able to access the user object without the url changing

### Reproduction

- Main:
```js
import { createApp } from 'vue'
import App from './App.vue'
import './index.css'

import { Router } from './router'
import { createAuth0 } from '@auth0/auth0-vue'

const app = createApp(App)

app.use(Router)

app.use(
  createAuth0({
    domain: 'dev------ahp.eu.auth0.com',
    client_id: 't3yYlTZSQaXI---------mfLomTovUn',
    redirect_uri: 'http://localhost:3000',
  })
)

app.mount('#app')
```

- Router:
```js
import { createRouter, createWebHistory } from 'vue-router'
import index from '../pages/index.vue'
import otherpage from '../pages/otherpage.vue'

const routes = [
  {
    path: '/',
    meta: { title: 'Home' },
    component: index,
  },
  {
    path: '/otherpage',
    component: otherpage,
  },
]

export const Router = createRouter({
  scrollBehavior: () => ({ left: 0, top: 0 }),
  history: createWebHistory(),
  routes,
})
```

- Index: 
```js
<script setup lang="ts">
  import { useAuth0 } from '@auth0/auth0-vue'

  const { loginWithRedirect, logout, user } = useAuth0();

  function logoutUser() {
    logout({returnTo: window.location.origin})
  }
</script>

<template>
  <div class="flex flex-col items-center">
    <div class="min-h-full flex flex-row items-center justify-center">
      <button class="px-2 py-1 bg-blue-500 text-white" @click="loginWithRedirect">Login</button>
      <button class="px-2 py-1 bg-blue-500 text-white" @click="logoutUser">Logout</button>
      <a href="/otherpage">Go to different page</a>
    </div>
    <pre v-if="user">
      <code>{{ user }}</code>
    </pre>
    <pre v-else>
      { }
    </pre>
  </div>
</template>
```

- Otherpage:
```js
<script setup lang="ts">
  import { useAuth0 } from '@auth0/auth0-vue'

  const { idTokenClaims } = useAuth0();
</script>

<template>
  <div class="flex flex-col items-center">
    <div class="min-h-full flex flex-row items-center justify-center">
      <a href="/">Go back</a>
    </div>
    <pre>{{ idTokenClaims }}</pre>
  </div>
</template>

```
**Can the behavior be reproduced using the [Vue SDK Playground](https://github.com/auth0/auth0-vue/blob/master/DEVELOPMENT.md#the-sdk-playground)?** The SDK Playground does not run on my machine for some reason

### Environment

- **Version of `auth0-vue` used:** 1.0.0-beta.2
- **Version of `vue` used:** 3.2.25
- **Which browsers have you tested in?** Firefox
- **Other modules/plugins/libraries that might be involved:** vue-router

**Comment by frederikprijck** [comment]
Thanks for reporting. Please replace `<a>` elements with Vue's `<router-link>`, that should not redirect.

If that doesnt solve it, please reproduce it in https://github.com/auth0-samples/auth0-vue-samples/tree/beta/01-Login so we can easily look into it.

**Comment by dukesteen** [comment]
> 

This fixed it, thank you so much :)
