### ISSUE TITLE
Browser URL is replaced with / after refreshing the browser

### ISSUE THREAD

**Issue by Soviut** [auth0/auth0-vue#88]
### Describe the problem

When I refresh my site the URL in the browser is replaced with `/` shortly after the page loads. eg: `http://localhost:3000/whatever` is replaced with `http://localhost:3000`. This is a replace since no redirect occurs.

### What was the expected behavior?

The URL should remain the same after a refresh.

### Reproduction

Removing the `createAuth0` plugin installation in `main.ts` stopped the URL from changing.

It seems to be caused by this line https://github.com/auth0/auth0-vue/blob/main/src/plugin.ts#L58
I was able to comment out that line and the URL stopped changing.

### Environment

- **Version of `auth0-vue` used: @auth0/auth0-vue@1.0.0-beta.0
- **Version of `vue` used: vue@3.2.31
- **Which browsers have you tested in? Chrome
- **Other modules/plugins/libraries that might be involved: vue-router

**Comment by frederikprijck** [comment]
Thanks, will look into this and provide a fix!

**Comment by Soviut** [comment]
@frederikprijck thanks, I could make a PR to remove it, I'm just not sure what the rationale is for it.

**Comment by frederikprijck** [comment]
The general idea here is that Auth0 will redirect back to your application, including certain query params.
Once we have used the params and exchanged them for tokens, we want to remove them from the URL.

I do believe we need to change how we are doing this, but I can't exactly reproduce your behavior.

Would you be able to give a but more information to help us reproduce and fix this?

Based on what you are saying is happening, I believe we should change the `__checkSession` function to this:
```
  private async __checkSession(proxy: Auth0VueClient) {
    const search = window.location.search;

    if (
      (search.includes('code=') || search.includes('error=')) &&
      search.includes('state=') &&
      !this.pluginOptions?.skipRedirectCallback
    ) {
      const res = await proxy.handleRedirectCallback();
      window.history.replaceState(
        {},
        document.title,
        res?.appState?.target || window.location.pathname
      );
    } else {
      await proxy.checkSession();
    }
  }
```
Would you be able to verify if using that would solve this for you ?

**Comment by Soviut** [comment]
I am using history mode.

I was thinking the same thing regarding the code; if the replace needs to stay, it should only be done when handling the callback.

Worth noting, I'm also using `skipRedirectCallback: true` so that I can do more work on my callback page (as mentioned in the other issues). So this suggested change will play nicely with it.

I'll update my PR shortly.

**Comment by frederikprijck** [comment]
I am not convinced that the change I added above is all we need. This might need a bit more investigation in terms of history mode vs hash mode.

If you have any suggestion to cover this for both situations, I am all ears.

**Comment by Soviut** [comment]
I have very little experience with hash mode but I'm definitely willing to help work through it.

**Comment by frederikprijck** [comment]
I pushed a commit to your PR that I believe should solve things for both hash-based and history-based routing.
