### ISSUE TITLE
Calling handleRedirectCallback() manually should not redirect router when skipRedirectCallback is true

### ISSUE THREAD

**Issue by Soviut** [auth0/auth0-vue#93]
### Describe the problem

I have set `skipRedirectCallback: true` in the plugin options. When I call `handleRedirectCallback()` it works, but it triggers a redirect.

I need to perform some additional work after the handler (fetching tokens, putting user data in my store, etc) then redirect manually. However, the forced redirect won't allow this (at least, not in a `<script setup>` SFC).

### What was the expected behavior?

No redirect should happen. I should be able to get the result back from the `handleRedirectCallback()`, do my additional work, then manually tell the router to redirect.

When `skipRedirectCallback` is true, the following lines should be skipped https://github.com/auth0/auth0-vue/blob/fb4819e3136b516544f0f5dd76e091670e0f854b/src/client.proxy.ts#L115-L122

### Workaround

I'm using the `<script setup>` approach instead of a `setup()` function for my Callback page. Any code that comes after calling `handleRedirectCallback()`  crashes because it goes out of scope as the route changes and the page is destroyed.

I found that if I wrap the handler and my code in a function and call it, the function stays in scope long enough to survive the redirect.

```typescript
const handleCallback = async () => {
  await handleRedirectCallback()
  const account = await models.account.get('a01')
  store.setAccount(account)
}
```

However, this still doesn't let me perform my own router redirect manually.

### Environment

- **Version of `auth0-vue` used: `@auth0/auth0-vue@1.0.0-beta.2`
- **Version of `vue` used: `vue@3.2.31`
- **Which browsers have you tested in? Chrome
- **Other modules/plugins/libraries that might be involved: vue-router

**Comment by frederikprijck** [comment]
This is currently fixed in https://github.com/auth0/auth0-vue/pull/89
