### ISSUE TITLE
DOCS The Vue Login guide has a typo in the "register the plugin" code example

### ISSUE THREAD

**Issue by Soviut** [auth0/auth0-vue#98]
### Describe the problem

On the [Vue Login guide](https://auth0.com/docs/quickstart/spa/vuejs/01-login#register-the-plugin) in the "Register the Plugin" section, there is a code snippet that shows the `clientId` being defined as camel case, while the plugin (and `Auth0VueClientOptions` type) expects `client_id` snake case.

```javascript
app.use(
  createAuth0({
    domain: "YOUR_DOMAIN",
    clientId: "YOUR_CLIENT_ID",
    redirect_uri: window.location.origin
  })
);
```

This also shows up in the "SPA quickstart" instructions for Vue, except the domain and client id are filled in.
The quickstart is found at `https://manage.auth0.com/dashboard/us/gofile/applications/<appid>/quickstart`

### What was the expected behavior?

In the short term, the docs should be updated to use `client_id` snake case.

```javascript
app.use(
  createAuth0({
    domain: "YOUR_DOMAIN",
    client_id: "YOUR_CLIENT_ID",
    redirect_uri: window.location.origin
  })
);
```

However, in the long term, it would be nice if all snake case variables had camel case aliases too (including `client_id` and `redirect_uri`).

### Reproduction

Visit https://auth0.com/docs/quickstart/spa/vuejs/01-login#register-the-plugin

### Environment

N/A

**Comment by frederikprijck** [comment]
Thanks for catching this.

Let me elaborate a bit on the snake case vs camelCase ... We prefer camelCase as well, but we have decided to stick to what Auth0-SPA-JS uses. We have a new major we would like to eventually get to for Auth0-SPA-JS (no ETA tho), which would also get rid of some snake_casing. Once that's done, we will follow with our other SDKs.

I opened a PR to fix this in our docs repository, closing this one here.
